---
kind: pipeline
type: docker
name: razworks build

steps:
  - name: build
    image: node:latest
    commands:
     - npm install
     - npm run lint
     - npx gridsome build
    when:
      branch:
        - develop
  - name: deploy
    image: lucap/drone-netlify
    settings:
      token:
        from_secret: netlify_token
      site_id:
        from_secret: site_id
      path: ./dist
    when:
      branch:
        - develop
