---
kind: pipeline
type: docker
name: razworks build

steps:
  - name: build
    image: node:latest
    commands:
     - npm install
     - npm run lint
     - npx gridsome build
    when:
      branch:
        - develop
