backend:
  name: github
  repo: RazorSiM/razworks
  branch: netlify

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - label: "Keycaps"
    name: "keycaps"
    folder: "content/keycaps"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Page URL", name: "pageURL", widget: "string" }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Kits"
        name: "kits"
        widget: "list"
        allow_add: true
        fields:
          - label: "Kit"
            name: "kit"
            widget: object
            fields:
              - label: 'Name'
                name: 'name'
                widget: "string"
              - label: 'Image'
                name: 'image'
                widget: image